[package]
name = "uwu-atag"
version.workspace = true
edition.workspace = true

[dependencies]
clap = { version = "4.5", features = ["derive"] }
colored = "2.1"
lofty = "0.22"
log = "0.4"
pretty_env_logger = "0.5"
