[package]
name = "uwu-pdf"
version.workspace = true
edition.workspace = true

[dependencies]
clap = { version = "4.5.53", features = ["derive"]}
log = "0.4.29"
lopdf = "0.38.0"
pretty_env_logger = "0.5.0"
colored = "2.2.0"
